### ISSUE TITLE
Design + your goals?

### ISSUE THREAD

**Issue by Gnomorian** [Energy0124/MCFreedomLauncher#10]
i ran the freedom launcher, part from being able to select where minecraft installs which is nice, nothing is different, the gui is identical, profiles are the same, does it run funny on linux, or is that intended?

**Comment by Energy0124** [comment]
It is intended to be same as the as the official launcher. In the older version of the launcher it also support other languages, but as some point the official launcher changed dramatically. As I do not have have to maintain the translation, I removed that function. I actually want to improve the launcher based on the official version, but I seldom play minecraft now and I am also busy with other projects, so it is almost the same with the official launcher now.

**Comment by Gnomorian** [comment]
fair enough, thanks for the reply.
