### ISSUE TITLE
Cracked launcher don't launch forge

### ISSUE THREAD

**Issue by lefgolas** [Energy0124/MCFreedomLauncher#11]
Hi! Like all the other cracked launcher, mcfreedom can't launch forge! we have the issue:
Exeption in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
Can you resolve this please ?

**Comment by AsukaLangleyfag** [comment]
Strange, because I've used MCFreedomLauncher with forge many times and it worked. 
Tried right now and it works (installed 1.10.2 from launcher, installed forge with forge installer and started the instance). Maybe, you can give more information?

**Comment by Energy0124** [comment]
I think it is working now, and this is a very old issue. I will close this issue.
