### ISSUE TITLE
Minecraft 1.9 / An update to your launcher is available and is required to play 1.9. Please restart your launcher.

### ISSUE THREAD

**Issue by meoso** [Energy0124/MCFreedomLauncher#12]
[15:07:14 ERROR]: An update to your launcher is available and is required to play 1.9. Please restart your launcher.

I realize you no longer support MCFreedomLauncher, however, it is "the best".  Would you point me in a direction to update the source to fix or bypass this issue?  I see the code that prints this error, but i'm unsure how/where to update for launcher 1.6.61

**Comment by Energy0124** [comment]
I have updated it with a simple hack to remove version check, just download the new release(v1.5.2) and it should works. Sorry that I am really busy with my study so I don't really have time to update it before. I never thought there are still people using it, so thank you for letting me know and telling me that it is "the best"! It feels pretty great :P (although I know it is really not the best)

**Comment by meoso** [comment]
I call it `the best`, because it is simple and straight forward, no bloat and no junk involved.  i love it that way.  Thank you very much!
