### ISSUE TITLE
Minecraft 1.10 requires update for the launcher

### ISSUE THREAD

**Issue by AsukaLangleyfag** [Energy0124/MCFreedomLauncher#13]
Log: [00:58:18 ERROR]: An update to your launcher is available and is required to play 1.10.2. Please restart your launcher.
Just letting you know. Also, many thanks for developing it, I use it for 2 years now and it worked perfectly (still works damn good, but not for 1.10.2).

**Comment by Energy0124** [comment]
Thank you for your support! 
I just check the latest version but it is working for me, have you try it?
[https://github.com/Energy0124/MCFreedomLauncher/releases/tag/v1.5.2](https://github.com/Energy0124/MCFreedomLauncher/releases/tag/v1.5.2)

**Comment by AsukaLangleyfag** [comment]
Yup, works. (my version was without that last commit) Thank you.
