### ISSUE TITLE
The future of Freedom Launcher

### ISSUE THREAD

**Issue by LightWayUp** [Energy0124/MCFreedomLauncher#16]
@Energy0124 
Looking at the timeline of this launcher, I see that it was actively maintained for a long time, with improvements like dual language selection, online mode (premium mode), installation directory selection and more. But ever since the drastic change to the official launcher, this project seems to have been abandoned because of lack of attention and support. Do you have any future plan for the launcher? And please allow me to be the collaborator (co maintainer) for this project, because I think it would be great if this launcher can be revived.

( P.S. I don't know where to write this so I opened an issue. )

**Comment by Energy0124** [comment]
@LightWayUp Hi, thanks for bringing up this issue. Personally, I don't have any plan for this project. Part of the reason that I abandoned this project is that I don't play much Minecraft now, so I don't have much incentive to continue this project. As I also have many other planned projects to work on, I don't have much time to maintain this project. If you are interested in contributing to this project, I am happy to add you as a collaborator. Thank you for your support! I am really glad that you would like to pick up this project.
