### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by LightWayUp** [Energy0124/MCFreedomLauncher#17]
In [YggdrasilAuthenticationService.java](https://github.com/Energy0124/MCFreedomLauncher/blob/beta/src/main/java/com/mojang/authlib/yggdrasil/YggdrasilAuthenticationService.java), the "access token" is *68e6e1faeb3e442097e1b45d2b3a577e*. Where is this from? Can it be replaced?

**Comment by Energy0124** [comment]
Yes, you can replace it. It is some dirty hard coded token just as a placeholder.

**Comment by LightWayUp** [comment]
The access token seems to not be authenticated in offline mode, which means any 32-character hex value will work. For now, I'll replace it with 0s until I come up with a better idea lol.
