### ISSUE TITLE
Can't create branch off non-default branch

### ISSUE THREAD

**Issue by LightWayUp** [Energy0124/MCFreedomLauncher#18]
Is it true that collaborators can only create new branches based on the default branch? I created a new one based on `master` to start updating launcher source to 1.6.73-j ( now `beta` is default and is 1.5.2 ) but when I tried pushing the commit ( new branch + new source ) I got an authentication error saying I don't have enough permission... Any idea how to solve?

**Comment by Energy0124** [comment]
I don't think there is such an restriction. I checked the git documentation but it isn't clear about that. 
However, I don't recommend you to update based on master as it is outdated. The beta branch is more updated and it should be easier to update from it.

**Comment by LightWayUp** [comment]
From the GitHub Desktop documentation, it says
> If you have collaborator permissions on a repository, you can create a branch off of the repository's __default__  branch so you can safely experiment with changes.

:(
I've already done some commits but can't push to repo… should I undo the commits? ( I'm not even sure if it's possible to undo branch creation… )

**Comment by LightWayUp** [comment]
Turns out it's the fault of buggy GitHub Desktop :(, solved by signing out and back in. Still, thanks for the response!
