### ISSUE TITLE
1.6.73-j stuck on loading versions...

### ISSUE THREAD

**Issue by LightWayUp** [Energy0124/MCFreedomLauncher#19]
A heads-up if anyone tries to compile source of 1.6.73-j. It will compile and the launcher will run, but version list will never load. Not sure what caused this but I'll try to fix the bug if I have time.

**Comment by ShotGunRaids** [comment]
The script.... Seems to be lacking these points. Adding a few things may help.     P.S. am nomin123

**Comment by ShotGunRaids** [comment]
What is the location of the argument's file

**Comment by LightWayUp** [comment]
> What is the location of the argument's file

Thanks for looking into this issue, but what argument's file are you referring to?

**Comment by LightWayUp** [comment]
I decompiled with Procyon instead, it's apparently much better than FernFlower. I'm now correcting mistakes in the code (again) made by the decompiler, and updating the code to not use deprecated stuff (again). I hope that'll solve the issue. Right now with FernFlower's version I can't even get through the do/while/iterator jungle.

**Comment by LightWayUp** [comment]
The issue has been fixed. I will update the repository tomorrow. Thanks to everyone who investigated the issue.
