### ISSUE TITLE
Default branch and GitHub pages

### ISSUE THREAD

**Issue by LightWayUp** [Energy0124/MCFreedomLauncher#20]
@Energy0124 :
I've been working on managing the repository's stuff recently.

I cleaned up the old `master` branch for newer code, but then realized it was so old that everything became a little hard to manage, so I removed the branch. I noticed `gh-pages` was unmaintained, and the actual page's font rendering wasn't that good ( maybe because of the custom font defined in css? ), so I removed the branch as well.

I created a new **orphan** `master` branch, and migrated the code from `beta` to the new `master`. I also added a `/docs` folder in `master`, making it easier to manage GitHub pages than having a separate branch. Now, all the production code is in new `master`, and `beta` branch is going to be deprecated since everything has been migrated.
Please help me change the default branch to `master`, and configure the GitHub page to use `master/docs` instead of `gh-pages` branch in Settings. Thanks!

P.S. The GitHub page will be used as the news source for Launcher Releases tab. Now it says 404 because I removed the `gh-pages` branch.
P.P.S. I have **full backup** for the **old** `master` and `gh-pages` branch. Do you want to keep them...?

**Comment by Energy0124** [comment]
No problem, I have changed the default branch to `master` and configured the GitHub page to use `master/docs`. Thanks for keeping the backup. I do have backups of the old `master `and `gh-pages` myself so you don't need to send them to me. Thank you for all the great improvements you made :)

**Comment by LightWayUp** [comment]
Thanks 😃!
