### ISSUE TITLE
Frames

### ISSUE THREAD

**Issue by Finguimbrine** [Energy0124/MCFreedomLauncher#28]
How do I edit the frames of the launcher, i can not edit only with the java files, thats why i prefer javafx

**Comment by LightWayUp** [comment]
Including JavaFX as dependency would further complicate build process and significantly increase final artifact size.  
You can use UI builders included in some IDEs to automatically generate the UI you want.

A note : the tab with JavaFX Webview for viewing news is being phased out in favor of the News Carousel which does not require JavaFX and fetches data from minecraft.net RSS feed and minecraft.net site through HTML parsing. I'm currently experimenting with it, but it's quite broken in the current state and I can't release it.
