### ISSUE TITLE
How would one update this to work with...

### ISSUE THREAD

**Issue by meoso** [Energy0124/MCFreedomLauncher#9]
How would one update this to work with latest Optifine+Liteloader. (if i wanted to attempt this).

Working with Liteloader 1.8 & OptiFine but only up to OptiFine 1.8.0 HD U B4.  A few newer releases of OptiFine are available. 

http://www.optifine.net/downloads
http://jenkins.liteloader.com/job/LiteLoaderInstaller/

(I did not try recompiling, would that be all that's necessary?)

**Comment by meoso** [comment]
given enough time, i tend to fix my crap.  Your current source actually works.  i was forced to delete all my ~/.minecraft/versions/* and recreate them.  it works with LiteLoader 1.8 and Optifine 1.8 **_C2_**

**Comment by Energy0124** [comment]
Sorry I missed your issue again, but I don't think this is a bug related to the launcher. Anyway, I am glad that you solved it yourself.
